// eslint-disable-next-line
export default {
  LOAD_JOURNAL_ENTRIES: "LOAD_JOURNAL_ENTRIES",
  UPDATE_JOURNAL_ENTRY: "UPDATE_JOURNAL_ENTRY",
  CREATE_JOURNAL_ENTRY: "CREATE_JOURNAL_ENTRY",
  DELETE_JOURNAL_ENTRY: "DELETE_JOURNAL_ENTRY",
  LOAD_USERS: "LOAD_USERS",
  CREATE_USER: "CREATE_USER",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",
};
